### ISSUE TITLE
[Reporting a Bug] General Setting is not Updating

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Hashnode/support#19]
- Made changes in the General setting and then clicked on the update button to save changes but it shows please check input fields before updating but input fields are filled!

![Screenshot (707)](https://user-images.githubusercontent.com/53345517/110198005-47742700-7e75-11eb-83d6-998a12c5e618.png)
 
 Am  I missing something? 😅

**Comment by fazlerocks** [comment]
This repo is for https://support.hashnode.com/

Closing the issue.
