### ISSUE TITLE
dependency problem in yarn

### ISSUE THREAD

**Issue by natesire** [Hashnode/support#26]
The dependent packages use google analytics. But I think they might be using the wrong version.

```yarn build```

results in 

Cannot find module '@docusaurus/plugin-google-analytics'

https://yarnpkg.com/package/@docusaurus/plugin-google-analytics

The alpha versions are different. Yarn's registry repo uses 2.0.0-alpha.75

But the project is trying to call 2.0.0-alpha.70

**Comment by Megha-Pathak** [comment]
This is resolved @natesire 
You can't find `@docusaurus/plugin-google-analytics` because it is not needed since we already had `@docusaurus/preset-classic`
