### ISSUE TITLE
Typo: Support guide docs

### ISSUE THREAD

**Issue by ayobami11** [Hashnode/support#27]
The highlighted text (astricks) in the image below should be 'asterisks'.

![Screenshot_20210521-214144_2](https://user-images.githubusercontent.com/64645351/119199014-3ef9b880-ba82-11eb-9692-25a2fdf41b71.png)

**Comment by didicodes** [comment]
Thanks for reporting @ayobami11. We will fix the typo. 

Please note that this repository is for [Hashnode's support documentation](https://support.hashnode.com/), not the [main product](http://hashnode.com/). So this isn't the right reposting to report this issue. Next time, send us a message on [Discord](https://discord.gg/qsAQfxX). Thank you. 😃
