### ISSUE TITLE
Add Issue and Pull Request Templates

### ISSUE THREAD

**Issue by sohamsshah** [Hashnode/support#38]
Issue and PR templates can help the contributors better define the problem they want to solve. 

In the recent github update, the `yml` files are also supported for templates; which make it even more easier to raise and discuss issues as it is more like a form. Though, both the markdown template and yml are equally good alternatives to choose.

Things that we can take care for issue/PR templates:
* Should be clear and precise
* Should not be tightly defined. Meaning, the users should easily be able to express their opinions in the issue instead of being bounded by the input/template fields.
* The maintainers can directly add the templates from the settings instead of manually creating a `.github` file. 
* [Configure](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) the template chooser page to also add contact links (in our case, discord or similar).

Let me know how does this sound. Thanks!

**Comment by Megha-Pathak** [comment]
As of now the details mentioned in the [Contributing guidelines](https://github.com/Hashnode/support/blob/main/CONTRIBUTING.md) seems good enough to guide people about what to include in their PRs and Issues. So, having a dedicated template is not a priority right now. But you want to take this issue up you can freely do so 👍🏻
I'll later link your PR to this issue if you decide to take this up.

**Comment by Evavic44** [comment]
> As of now the details mentioned in the [Contributing guidelines](https://github.com/Hashnode/support/blob/main/CONTRIBUTING.md) seems good enough to guide people about what to include in their PRs and Issues. So, having a dedicated template is not a priority right now. But you want to take this issue up you can freely do so 👍🏻 I'll later link your PR to this issue if you decide to take this up.

Hello, @Megha-Pathak is this still up for grabs? Can quickly add the templates.
