### ISSUE TITLE
Bug 🐛: Duplicate text in standard classes

### ISSUE THREAD

**Issue by saviomartin** [Hashnode/support#42]
**Describe the bug**
I found a bug in the [standard classes page](https://support.hashnode.com/docs/standard-classes). The word `blog-title` is added twice. 

**To Reproduce**

1. Go to [standard classes page](https://support.hashnode.com/docs/standard-classes)
2. Search for `blog-title`
3. You can see the word is added twice

**Expected behavior**
It only appears once in a page, so there should be just one, right?

Looking forward to what the team thinks to this? Cheers!

**Comment by projectashik** [comment]
Same for 
- blog-series-cover-container
- blog-series-cover
