### ISSUE TITLE
Bookmarks organizing feature [REQUESTED]

### ISSUE THREAD

**Issue by projektorius96** [Hashnode/support#44]
It would be nice to have an organizing feature for **Bookmarks** similarly to the feature that Pinterest has organizing boards.

Nevertheless hashnode is very lightweight  as a user I do appreciate I can share online . Stay alive fellas ! 👍🏼

**Comment by Megha-Pathak** [comment]
Hey, you can request the features related to [Hashnode](https://hashnode.com/) using [this section](https://hashnode.com/feature-requests). 

Issues here are limited to raised feature requests and issues related to the [Hashnode Support site](https://support.hashnode.com/).
