### ISSUE TITLE
Where are the hashnode api docs located?

### ISSUE THREAD

**Issue by philbannon** [Hashnode/support#68]
Hi all,

I'm looking to try and find the api documentation for hashnode. Can someone point me in the right direction?

**Comment by philipbannon** [comment]
Sorry please ignore this. The docs would not load for me on the sandbox page -- unable to click for example "user". Issue was with an outdated Chrome.

**Comment by philbannon** [comment]
Sorry please ignore this. The docs would not load for me on the sandbox page -- unable to click for example "user". Issue was with an outdated Chrome.
